Repository green-pinetree/picnic-map, pull requests merged in 2023-05, with the labels that each got.

#2 config: 프론트엔드 초기환경 설정 #1
  client/.eslintrc.json
  client/.gitignore
  client/.husky/pre-commit
  client/.husky/pre-push
  client/.pnp.cjs
  client/.pnp.loader.mjs
  client/.vscode/extensions.json
  client/.vscode/settings.json
  client/.yarnrc.yml
  client/README.md
  client/next.config.js
  client/package.json
  client/public/favicon.ico
  client/public/next.svg
  client/public/vercel.svg
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/api/hello.ts
  client/src/pages/index.tsx
  client/src/styles/Home.module.css
  client/src/styles/globals.css
  client/tsconfig.json
  client/yarn.lock
Labels: config

#4 Config/cicd/build test
  .github/pull_request_template.md
  .github/workflows/fe-test.yml
Labels: config

#9 Config/be/init setting
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/app/seok/picnicmap/MainController.java
  server/src/main/java/app/seok/picnicmap/PicnicMapApplication.java
  server/src/main/resources/application.properties
  server/src/test/java/app/seok/picnicmap/PicnicMapApplicationTests.java
Labels: config

#14 config: lint & prettier setting #11
  client/.eslintrc.json
  client/.gitignore
  client/.pnp.cjs
  client/.prettierrc.js
  client/.vscode/extensions.json
  client/.vscode/settings.json
  client/.yarn/plugins/@yarnpkg/plugin-typescript.cjs
  client/.yarn/releases/yarn-3.5.1.cjs
  client/.yarn/sdks/eslint/bin/eslint.js
  client/.yarn/sdks/eslint/lib/api.js
  client/.yarn/sdks/eslint/package.json
  client/.yarn/sdks/integrations.yml
  client/.yarn/sdks/prettier/index.js
  client/.yarn/sdks/prettier/package.json
  client/.yarn/sdks/typescript/bin/tsc
  client/.yarn/sdks/typescript/bin/tsserver
  client/.yarn/sdks/typescript/lib/tsc.js
  client/.yarn/sdks/typescript/lib/tsserver.js
  client/.yarn/sdks/typescript/lib/tsserverlibrary.js
  client/.yarn/sdks/typescript/lib/typescript.js
  client/.yarn/sdks/typescript/package.json
  client/package.json
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/index.tsx
  client/yarn.lock
Labels: config

#16 config: vite + react로 setting 변경 #15
  .DS_Store
  client/.eslintrc.cjs
  client/.eslintrc.json
  client/.gitignore
  client/.husky/pre-commit
  client/.husky/pre-push
  client/.pnp.cjs
  client/.prettierrc
  client/.prettierrc.js
  client/.vscode/settings.json
  client/.yarnrc.yml
  client/README.md
  client/index.html
  client/next.config.js
  client/package.json
  client/public/favicon.ico
  client/public/next.svg
  client/public/vercel.svg
  client/public/vite.svg
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/Home.tsx
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/api/hello.ts
  client/src/pages/index.tsx
  client/src/styles/Home.module.css
  client/src/styles/globals.css
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  client/yarn.lock
Labels: config

#17 Feat/fe/init setting: 프론트엔드 초기 환경 세팅
  .DS_Store
  client/.eslintrc.cjs
  client/.eslintrc.json
  client/.gitignore
  client/.husky/pre-commit
  client/.pnp.cjs
  client/.vscode/extensions.json
  client/.vscode/settings.json
  client/.yarn/sdks/prettier/index.js
  client/.yarn/sdks/prettier/package.json
  client/.yarnrc.yml
  client/README.md
  client/index.html
  client/next.config.js
  client/package.json
  client/public/favicon.ico
  client/public/next.svg
  client/public/vercel.svg
  client/public/vite.svg
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/Home.tsx
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/index.tsx
  client/src/styles/color.ts
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  client/yarn.lock
Labels: config

#23 Feat/fe/common components
  client/.eslintrc.json
  client/.husky/pre-commit
  client/.pnp.cjs
  client/.prettierrc
  client/package.json
  client/public/Icon.svg
  client/public/dummyimg.png
  client/public/favicon.ico
  client/public/favicon.svg
  client/src/components/SideBar.tsx
  client/src/components/common/Badge.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/DateDropDown.tsx
  client/src/components/common/DateInfo.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/PlaceInfo.tsx
  client/src/components/common/SearchBar.tsx
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/index.tsx
  client/src/styles/breakpoint.ts
  client/src/styles/color.ts
  client/src/styles/font.ts
  client/src/styles/global.ts
  client/src/styles/mixin.ts
  client/src/styles/theme.ts
  client/src/types/Theme.ts
  client/yarn.lock
Labels: feat

#26 Feat/fe/map api
  client/.pnp.cjs
  client/package.json
  client/src/components/DesktopSection.tsx
  client/src/components/Map.tsx
  client/src/components/MobileSection.tsx
  client/src/components/SideBar.tsx
  client/src/components/common/DateDropDown.tsx
  client/src/components/common/Header.tsx
  client/src/pages/_document.tsx
  client/src/pages/index.tsx
  client/src/styles/global.ts
  client/yarn.lock
Labels: feat

#35 Feat/fe/page: 페이지에 사용할 각 컴포넌트 구현
  client/.pnp.cjs
  client/package.json
  client/src/components/DesktopSection.tsx
  client/src/components/Drawer.tsx
  client/src/components/MobileSection.tsx
  client/src/components/SideBar.tsx
  client/src/components/common/Badge.tsx
  client/src/components/common/DateDropDown.tsx
  client/src/components/common/Detail.tsx
  client/src/components/common/Filter.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Map.tsx
  client/src/components/common/PlaceInfo.tsx
  client/src/components/common/SearchBar.tsx
  client/src/components/common/SearchContainer.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/styles/color.ts
  client/src/styles/global.ts
  client/src/styles/zIndex.ts
  client/yarn.lock
Labels: feat

#38 Feat/fe/api: 데이터 요청 로직 구현
  .github/workflows/fe-test.yml
  client/.eslintrc.json
  client/.gitignore
  client/.pnp.cjs
  client/next.config.js
  client/package.json
  client/public/dummy-image.jpg
  client/public/dummyimg.png
  client/public/marker.png
  client/src/components/DateInfo.tsx
  client/src/components/Detail.tsx
  client/src/components/Filter.tsx
  client/src/components/Layout/DesktopLayout.tsx
  client/src/components/Layout/MobileLayout.tsx
  client/src/components/PlaceInfo.tsx
  client/src/components/SearchContainer.tsx
  client/src/components/common/DateDropDown.tsx
  client/src/components/common/DateInfo.tsx
  client/src/components/common/Drawer.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Loading.tsx
  client/src/components/common/Map.tsx
  client/src/components/common/PlaceInfo.tsx
  client/src/components/common/SideBar.tsx
  client/src/constants/weather.ts
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/store/placeList.ts
  client/src/store/rootReducer.ts
  client/src/store/store.ts
  client/src/store/userLocation.ts
  client/src/store/weather.ts
  client/src/styles/color.ts
  client/src/styles/font.ts
  client/src/types/Response.ts
  client/src/utils/http.ts
  client/test.html
  client/yarn.lock
Labels: feat

#40 fix: import 순서 변경
  client/.eslintrc.json
  client/src/components/DateInfo.tsx
  client/src/components/Detail.tsx
  client/src/components/Filter.tsx
  client/src/components/Layout/DesktopLayout.tsx
  client/src/components/Layout/MobileLayout.tsx
  client/src/components/PlaceInfo.tsx
  client/src/components/SearchContainer.tsx
  client/src/components/common/Badge.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/DateDropDown.tsx
  client/src/components/common/Drawer.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Map.tsx
  client/src/components/common/SearchBar.tsx
  client/src/components/common/SideBar.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/store/placeList.ts
  client/src/store/rootReducer.ts
  client/src/store/store.ts
  client/src/store/weather.ts
  client/src/styles/font.ts
  client/src/styles/global.ts
  client/src/styles/theme.ts
  client/test.html
Labels: config

#41 Feat/fe/api
  client/.eslintrc.json
  client/src/components/DateInfo.tsx
  client/src/components/Filter.tsx
  client/src/components/Layout/DesktopLayout.tsx
  client/src/components/Layout/MobileLayout.tsx
  client/src/components/RenderPlaceList.tsx
  client/src/components/SearchContainer.tsx
  client/src/components/common/Badge.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/DateDropDown.tsx
  client/src/components/common/Map.tsx
  client/src/components/common/SearchBar.tsx
  client/src/constants/type.ts
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/store/index.ts
  client/src/store/renderList.ts
  client/src/store/rootReducer.ts
  client/src/store/searchList.ts
  client/src/store/typeFilter.ts
  client/src/styles/global.ts
Labels: feat

#42 fix: dispatch type generic #36
  client/src/components/SearchContainer.tsx
Labels: chore

#48 Feat/fe/api: api 붙이기 작업 완료
  client/.pnp.cjs
  client/package.json
  client/public/next.svg
  client/public/vercel.svg
  client/src/components/Detail.tsx
  client/src/components/Layout/DesktopLayout.tsx
  client/src/components/PlaceInfo.tsx
  client/src/components/RenderPlaceList.tsx
  client/src/components/SearchContainer.tsx
  client/src/components/common/Drawer.tsx
  client/src/components/common/Map.tsx
  client/src/components/common/SideBar.tsx
  client/src/pages/index.tsx
  client/src/store/centerLocation.ts
  client/src/store/mapBounds.ts
  client/src/store/placeList.ts
  client/src/store/renderList.ts
  client/src/store/rootReducer.ts
  client/src/store/searchList.ts
  client/src/types/Place.ts
  client/yarn.lock
Labels: feat

#50 Chore/fe/fix UI개선 & 추가 기능 구현
  client/src/components/Detail.tsx
  client/src/components/Layout/DesktopLayout.tsx
  client/src/components/Layout/MobileLayout.tsx
  client/src/components/RenderPlaceList.tsx
  client/src/components/SearchContainer.tsx
  client/src/components/common/Badge.tsx
  client/src/components/common/Drawer.tsx
  client/src/components/common/Map.tsx
  client/src/components/common/SearchBar.tsx
  client/src/hooks/useFetchDetail.ts
  client/src/hooks/useQueryString.ts
  client/src/hooks/useRenderList.ts
  client/src/hooks/useSetCenter.ts
  client/src/hooks/useUserLocation.ts
  client/src/pages/index.tsx
  client/src/store/placeList.ts
  client/src/store/searchList.ts
Labels: fix, feat, chore

#51 fix: import order
  client/.eslintrc.json
  client/src/components/common/Map.tsx
Labels: chore

#52 Chore/fe/fix UI
  client/src/components/Detail.tsx
  client/src/components/RenderPlaceList.tsx
  client/src/pages/index.tsx
Labels: chore

#53 Chore/fe/fix 메타테크 추가, placelist api 수정
  client/public/og_image.png
  client/src/pages/_document.tsx
  client/src/store/placeList.ts
Labels: chore

#54 chore: open graph 이미지 변경
  client/public/og_image.png
Labels: chore

#56 Chore/fe/fix ui/ux 피드백 반영
  client/src/components/common/Header.tsx
  client/src/components/common/SearchBar.tsx
Labels: chore

#57 chore: og-image 변경, 로고 클릭시 지도 가운데 위치도 초기화
  client/public/og_image.png
  client/src/components/common/Header.tsx
Labels: chore

#58 Docs/fe/readme : Readme 작성
  README.md
  client/src/components/SearchContainer.tsx
  client/src/components/common/Header.tsx
  client/src/hooks/useRenderList.ts
Labels: docs, chore

#60 refactor: 피드백 받은 부분 리팩토링
  client/.eslintrc.json
  client/src/components/DateInfo.tsx
  client/src/components/DetailBack.tsx
  client/src/components/Layout/MobileLayout.tsx
  client/src/components/PlaceInfo.tsx
  client/src/components/common/Drawer.tsx
  client/src/components/common/Header.tsx
  client/src/components/common/Map.tsx
  client/src/components/common/SearchBar.tsx
  client/src/pages/index.tsx
  client/src/styles/font.ts
  client/src/styles/global.ts
Labels: refactor

#61 chore: 헤더 ui 깨짐 오류 #59
  client/src/components/common/Header.tsx
Labels: chore
